"""init

Revision ID: 443e1ed0aef4
Revises: 
Create Date: 2026-04-21 03:17:41.257350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443e1ed0aef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('e2e_id', sa.String(length=50), nullable=True),
    sa.Column('doador_nome', sa.String(length=120), nullable=False),
    sa.Column('doador_email', sa.String(length=120), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_doacao', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('webhook_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doacoes_e2e_id'), ['e2e_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doacoes_e2e_id'))

    op.drop_table('doacoes')
    # ### end Alembic commands ###
